"""
Django settings for user_management project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# To keep secret keys in environment variables
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*'] 
# Redirect all HTTP traffic to HTTPS
SECURE_SSL_REDIRECT = False

# Enable secure cookies
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# Optionally, add HTTP Strict Transport Security (HSTS)
# SECURE_HSTS_SECONDS = 3600  # Adjust the seconds as needed
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True  # Optionally, for HSTS preload list
DATA_UPLOAD_MAX_MEMORY_SIZE = 1064 * 1024 * 1024  # 1064 MB request body parser limit
FILE_UPLOAD_MAX_MEMORY_SIZE = 1064 * 1024 * 1024 

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UserConfig',
    'social_django',
    "sslserver",
    'file_manager.apps.FileManagerConfig',
    'whm.apps.WhmConfig',
    'api.apps.ApiConfig',
    'admin_api.apps.AdminApiConfig',
]

# --- Dynamic plugin app loader ---
MODULES_DIR = os.path.join(BASE_DIR, 'modules')
if os.path.isdir(MODULES_DIR):
    for module_name in os.listdir(MODULES_DIR):
        module_path = os.path.join(MODULES_DIR, module_name)
        if os.path.isdir(module_path) and os.path.exists(os.path.join(module_path, '__init__.py')):
            INSTALLED_APPS.append(f'modules.{module_name}')


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'users.middleware.FirewallMiddleware.FirewallMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', 
    'whm.middleware.admin_dual_session.SeparateAdminSessionMiddleware',    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.LicenseMiddleware.LicenseMiddleware',

]

ROOT_URLCONF = 'user_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'users.context_processors.dynamic_plugins', 
                'users.context_processors.branding',
                'whm.context_processors.dynamic_plugins',
                'whm.context_processors.admin_user_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
def get_db_password(file_path):
    full_path = os.path.join(BASE_DIR, file_path)
    try:
        with open(full_path, 'r') as file:
            password = file.read().strip()  # Read the password and remove any surrounding whitespace
            return password
    except FileNotFoundError:
        return None
    except Exception as e:
        print(f"Error reading file {file_path}: {e}")
        return None  # Return None if there's an error

db_password = get_db_password('etc/mysqlPassword')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'panel',
        'USER': 'root',
        'PASSWORD': db_password,
        'HOST': '127.0.0.1',  # or '127.0.0.1'
        'PORT': '3306',       # MySQL default port
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = get_db_password('etc/time.zone') or 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = False  


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'


# social auth configs for github
SOCIAL_AUTH_GITHUB_KEY = str(os.getenv('GITHUB_KEY'))
SOCIAL_AUTH_GITHUB_SECRET = str(os.getenv('GITHUB_SECRET'))

# social auth configs for google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = str(os.getenv('GOOGLE_KEY'))
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = str(os.getenv('GOOGLE_SECRET'))

# email configs
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = str(os.getenv('EMAIL_USER'))
EMAIL_HOST_PASSWORD = str(os.getenv('EMAIL_PASSWORD'))

SESSION_COOKIE_AGE = 60 * 60 * 24
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SAVE = True 

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

# If you want to enforce HTTPS in your Django application
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

VERSION = get_db_password('etc/version')
MY_OS_NAME = get_db_password('etc/osName')
MY_OS_VERSION = get_db_password('etc/osVersion')

# ---- SESSION SETTINGS ----
SESSION_COOKIE_NAME = "sessionid" 
ADMIN_SESSION_COOKIE_NAME = "session_admin"   # admin users


SESSION_COOKIE_SECURE = False                 # set True in prod (HTTPS)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# Admin cookie mirrors the normal one (you can tweak)
ADMIN_SESSION_COOKIE_AGE = SESSION_COOKIE_AGE
ADMIN_SESSION_COOKIE_SECURE = SESSION_COOKIE_SECURE
ADMIN_SESSION_COOKIE_HTTPONLY = SESSION_COOKIE_HTTPONLY
ADMIN_SESSION_COOKIE_SAMESITE = SESSION_COOKIE_SAMESITE
