# Generated by Django 4.1.2 on 2024-10-11 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, null=True)),
                ('disk_space', models.IntegerField(default=0)),
                ('bandwidth', models.IntegerField(default=0)),
                ('email_accounts', models.IntegerField(default=0)),
                ('databases', models.IntegerField(default=0)),
                ('ftp_accounts', models.IntegerField(default=0)),
                ('allowed_domains', models.IntegerField(default=0)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('enforce_disk_limits', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='pkg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('php', models.CharField(max_length=255)),
                ('ssl_exp', models.CharField(max_length=255)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Dns_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('ttl', models.CharField(max_length=255)),
                ('prio', models.CharField(max_length=255)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
