# Generated by Django 4.1.2 on 2026-09-24 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_package_profile_pkg_id_domain_dns_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WHMCS', max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('startup_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'apps',
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('boolean', 'boolean'), ('json', 'json')], default='string', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='BackupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('userid', models.IntegerField()),
                ('schedule', models.CharField(blank=True, max_length=500, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('host', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('user_access', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'backup',
            },
        ),
        migrations.CreateModel(
            name='Bandwidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.IntegerField(default=0)),
                ('line', models.IntegerField(default=0)),
                ('userid', models.IntegerField()),
            ],
            options={
                'db_table': 'bandwidth',
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('block_type', models.CharField(choices=[('TEMP', 'Temporary'), ('PERM', 'Permanent'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
                ('temp_block_expires', models.DateTimeField(blank=True, null=True)),
                ('temp_block_count', models.IntegerField(default=0)),
                ('first_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'blocked_ip',
            },
        ),
        migrations.CreateModel(
            name='DbClusterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Database Node', max_length=255)),
                ('node_role', models.CharField(choices=[('primary', 'Primary (Master)'), ('replica', 'Replica (Standby)')], default='primary', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('mysql_port', models.IntegerField(default=3306)),
                ('api_port', models.IntegerField(default=30)),
                ('auth_token', models.CharField(blank=True, max_length=500, null=True)),
                ('repl_user', models.CharField(default='olspanel_repl', max_length=100)),
                ('repl_password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active & Replicating'), ('syncing', 'Syncing Baseline'), ('paused', 'Replication Paused'), ('error', 'Replication Error'), ('disconnected', 'Disconnected')], default='active', max_length=30)),
                ('is_local', models.BooleanField(default=False)),
                ('replicate_all', models.BooleanField(default=False, help_text='True = sync entire MySQL server, False = sync selected databases only')),
                ('selected_databases', models.TextField(blank=True, default='[]', help_text='JSON list of specific databases to replicate')),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('seconds_behind_master', models.IntegerField(blank=True, default=0, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'db_cluster_nodes',
            },
        ),
        migrations.CreateModel(
            name='DbReplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(blank=True, default='', max_length=128)),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_replication_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DbSyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active & Synced'), ('syncing', 'Initial Syncing'), ('paused', 'Paused'), ('error', 'Sync Error')], default='active', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'db_sync_rules',
            },
        ),
        migrations.CreateModel(
            name='EmailForword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('domain_id', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'email_forwardings',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('DiskUsage', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('domain_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'email_users',
            },
        ),
        migrations.CreateModel(
            name='FilterBlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
                ('first_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('temp_block_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'blocked_filter_ip',
            },
        ),
        migrations.CreateModel(
            name='Ftps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
                ('uid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('dir', models.CharField(max_length=255)),
                ('QuotaSize', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
                ('ULBandwidth', models.IntegerField()),
                ('DLBandwidth', models.IntegerField()),
                ('sate', models.DateField()),
                ('LastModif', models.CharField(max_length=255)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('domain_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ftp',
            },
        ),
        migrations.CreateModel(
            name='SSOToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sso_tokens',
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'timezone',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pkg_id',
        ),
        migrations.AddField(
            model_name='domain',
            name='line',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='allowed_subdomains',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Security Key / Passkey', max_length=100)),
                ('credential_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, max_length=64, null=True)),
                ('transports', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_passkeys',
            },
        ),
        migrations.AddIndex(
            model_name='ssotoken',
            index=models.Index(fields=['user_id'], name='sso_tokens_user_id_8e7923_idx'),
        ),
        migrations.AddField(
            model_name='dbsyncrule',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database_rules', to='users.dbclusternode'),
        ),
        migrations.AddField(
            model_name='dbreplicationlog',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.dbclusternode'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dbsyncrule',
            unique_together={('node', 'database_name')},
        ),
    ]
