# Generated by Django 4.1.2 on 2026-09-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_apikey_apps_appsettings_backuplist_bandwidth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbclusternode',
            name='channel_name',
            field=models.CharField(default='default', help_text='MariaDB multi-source channel identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='dbclusternode',
            name='rewrite_rules',
            field=models.TextField(blank=True, default='{}', help_text='JSON map of source_db -> target_db name rewrites'),
        ),
        migrations.AddField(
            model_name='dbclusternode',
            name='ignore_tables',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of table wildcard ignore patterns'),
        ),
        migrations.AddField(
            model_name='dbclusternode',
            name='auto_cloned',
            field=models.BooleanField(default=False, help_text='Whether initial data baseline has been cloned'),
        ),
        migrations.AddField(
            model_name='dbsyncrule',
            name='channel_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='dbsyncrule',
            name='target_database_name',
            field=models.CharField(blank=True, default='', help_text='Target DB name on replica if rewritten', max_length=128),
        ),
        migrations.AddField(
            model_name='dbsyncrule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_databases', to=settings.AUTH_USER_MODEL),
        ),
    ]
