# Generated by Django 4.1.2 on 2026-09-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dbclusternode_alter_userpasskey_credential_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbclusternode',
            name='replicate_all',
            field=models.BooleanField(default=False, help_text='True = sync entire MySQL server, False = sync selected databases only'),
        ),
        migrations.AddField(
            model_name='dbclusternode',
            name='selected_databases',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of specific databases to replicate'),
        ),
        migrations.AddField(
            model_name='dbreplicationlog',
            name='database_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='DbSyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active & Synced'), ('syncing', 'Initial Syncing'), ('paused', 'Paused'), ('error', 'Sync Error')], default='active', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database_rules', to='users.dbclusternode')),
            ],
            options={
                'db_table': 'db_sync_rules',
                'unique_together': {('node', 'database_name')},
            },
        ),
    ]
