# Status 1 for active 0 for Deactive
STATUS = 1

LOG_FILE = /var/log/syslog, /var/log/messages, /var/log/pureftpd.log, /var/log/pure-ftpd/pure-ftpd.log

DATA_FILE = /usr/local/ufw/db/

# Keep Temporary block time in minutes
TEMP_BLOCK_DURATION = 10

# Count Attempts for block
TEMP_BLOCK_THRESHOLD = 12

# block Temporary if Attempts reach (TEMP_BLOCK_THRESHOLD) Attempts within minutes
TEMP_WINDOW = 5

# Attempts for Permanently blocks     
PERM_BLOCK_THRESHOLD = 20  

# Permanently blocks if Attempts reach (PERM_BLOCK_THRESHOLD) within hours
PERM_WINDOW = 24
# match for detecte failure
KEYWORD = Failed password, Invalid user, invaild, wrong,authentication failure,Login failed,Invalid password,Authentication failed,FAIL LOGIN,password mismatch,authenticator failed
  
#Ignore ip
IGNORE_IP=127.0.0.1,127.0.0.0